config/routes.rb
TFG::Application.routes.draw do

  resources :dispositivofisicos

  resources :parametros

  resources :estilos

  resources :listareproducions

  resources :dispositivoloxicos

  resources :subformatos

  resources :diapositivas

  resources :campos

  resources :formatos

  resources :diapositivas_listareproducions

  resources :uploads
  
  match "/diapositivas_listareproducions/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/listareproducions/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/listareproducions/:id/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/diapositivas/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/diapositivas/:id/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")

  match "public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")

  match "/listareproducions/public/listas/:lista/:diapositiva" => redirect("/listas/%{lista}/%{diapositiva}")
  match "/listareproducions/:id/public/listas/:lista/:diapositiva" => redirect("/listas/%{lista}/%{diapositiva}")
  match "/public/listas/:lista/:diapositiva" => redirect("/listas/%{lista}/%{diapositiva}")

  match "dispositivofisicos/public/dispositivos/:dispositivo/inicio.html" => redirect("/dispositivos/%{dispositivo}/inicio.html")
  match "/dispositivos/:dispositivo/public/listas/:lista/:diapositiva" => redirect("/listas/%{lista}/%{diapositiva}")
  
  post 'listareproducions/:id/edit', :controller => 'listareproducions', :action => 'edit', :id => '%{id}'
  post 'diapositivas/uploadFile'
  post 'uploads/uploadFile'

  post 'campos/desvincular'

end

app/models/diapositivas_listareproducion.rb
class DiapositivasListareproducion < ActiveRecord::Base
  attr_accessible :diapositiva_id, :listareproducion_id, :factorTempo, :orde
  belongs_to :diapositiva
  belongs_to :listareproducion
 end

app/controllers/diapositivas_listareproducions_controller.rb
# encoding: utf-8

class DiapositivasListareproducionsController < ApplicationController
  def new
    @listareproducion = Listareproducion.find(params[:lista])
    @listareproducion_diapositivas = Array.new
    #Almacenamento dos formatos das diapositivas
    @listareproducion_formatos = Array.new
    @listareproducion_rexistros = DiapositivasListareproducion.find_all_by_listareproducion_id(@listareproducion.id)

    @listareproducion_rexistros.each do |rexistro|
      @listareproducion_diapositiva = Diapositiva.find(rexistro.diapositiva_id)
      @listareproducion_diapositivas << @listareproducion_diapositiva
      @listareproducion_formatos << Formato.find(@listareproducion_diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_campos_formatos_formato_id)
    end
    
    #Búsqueda do tipo de dispositivo para o que foi deseñada, se xa ten diapositivas
    if !@listareproducion_diapositivas.empty?
      @diapositiva = Diapositiva.find(@listareproducion_diapositivas[0])
      @diapositiva_formato = @diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_campos_formatos_formato_id
      @diapositiva_subformato = @diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_subformato_id
      @dispositivo = Subformato.find(@diapositiva_subformato).dispositivoloxico

      #Búsqueda de diapositivas que foron deseñadas para o dispositivo
      @subformatos = Subformato.find_all_by_dispositivoloxico_id(@dispositivo.id)
      #Extráense as entradas da táboa campos - formatos - subformatos - diapositivas que indiquen que as diapositivas son dos subformatos escollidos
      @diapositivas = Array.new
      #Extráense os formatos das diapositivas
      @diapositivas_formatos = Array.new
      #Gárdanse os ids das diapositivas para ser opcións do select na vista
      @opcionsSelect = Array.new
      @subformatos.each do |subformato|
        #Só se necesita o id da diapositiva, e con unha vez resulta suficiente
        @rexistros = CamposFormatosSubformatosDiapositiva.where(:campos_formatos_subformatos_subformato_id => subformato.id).select(:diapositiva_id).uniq
        @rexistros.each do |rexistro|
          #Recóllense os datos da diapositiva e introdúcese nun array
          @diapositiva = Diapositiva.find(rexistro.diapositiva_id)
          #Compróbase que a diapositiva non forme parte xa da lista de reprodución
          if !@listareproducion_diapositivas.include?(@diapositiva)
            @diapositivas << @diapositiva
            @formato = Formato.find(@diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_campos_formatos_formato_id)
            @diapositivas_formatos << @formato
            @opcionsSelect << @diapositiva.id
          end
        end
      end
    #Senón, preséntanse todas as diapositivas creadas
    else
      #Todas as diapositivas
      @diapositivas = Diapositiva.all
      #Todos os dispositivos
      @dispositivos = Array.new
      #Opcións para presentar
      @opcionsSelect = Array.new
      #Para cada diapositiva, cóllese o seu dispositivo
      @diapositivas.each do |diapositiva|
        @diapositiva_subformato = diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_subformato_id
        @dispositivo = Subformato.find(@diapositiva_subformato).dispositivoloxico
        @dispositivos << @dispositivo
        @opcionsSelect << diapositiva.id
      end
    end
  end

  def create
    #Datos recibidos
    @factorTempo = params[:factorTempoDiapositiva]
    @diapositiva_id = params[:diapositiva]
    @diapositiva = Diapositiva.find(@diapositiva_id)
    @listareproducion_id = params[:id]
    @listareproducion = Listareproducion.find(@listareproducion_id)
    
    #Recupérase a lista de repdrodución enteira (todos os rexistros de diapositivas - listareproducions)
    @rexistros = DiapositivasListareproducion.find_all_by_listareproducion_id(@listareproducion_id)
    
    #Nova posición na lista
    @novaOrde = @rexistros.length + 1

    #Engádese a entrada na táboa da relación diapositivas - listareproducions
    DiapositivasListareproducion.create!(:diapositiva_id => @diapositiva_id, :listareproducion_id => @listareproducion_id, :factorTempo => @factorTempo, :orde => @novaOrde)

    #Copiar diapositiva á carpeta da lista
    FileUtils.cp "public/contidos/#{params[:diapositiva]}.html", "public/listas/#{@listareproducion.id}"


    #Correxir a diapositiva anterior e a actual, no caso de que existan máis de unha
    @numeroDiapositivas = DiapositivasListareproducion.find_all_by_listareproducion_id(@listareproducion_id)
    if @numeroDiapositivas.length > 1
      #Facer que a anterior apunte á actual e a actual á primeira
      @rexistroAnterior = DiapositivasListareproducion.find_by_listareproducion_id_and_orde(@listareproducion_id,@novaOrde-1)
      @rexistroActual = DiapositivasListareproducion.find_by_listareproducion_id_and_orde(@listareproducion_id,@novaOrde)
      @rexistroPrimeiro = DiapositivasListareproducion.find_by_listareproducion_id_and_orde(@listareproducion_id,1)
      @diapositivaAnterior = Diapositiva.find(@rexistroAnterior.diapositiva_id)
      @diapositivaPrimeira = Diapositiva.find(@rexistroPrimeiro.diapositiva_id)

      #Configuración do ficheiro
      @path = "public/listas/#{@listareproducion.id}/"
      @pathCompleto = "http://localhost:3000/public/listas/#{@listareproducion.id}/"
      @extension = ".html"

      #Nomes das diapositiva anterior, actual, e primeira
      @nomeAnterior = @diapositivaAnterior.id.to_s
      @nomeActual = @diapositiva.id.to_s
      @nomePrimeira = @diapositivaPrimeira.id.to_s

      #Paths das diapositivas anterior e actual
      @nomeFicheiroAnterior = @path + @nomeAnterior + @extension
      @nomeFicheiroActual = @path + @nomeActual + @extension
      @nomeFicheiroPrimeiro = @path + @nomePrimeira + @extension

      #Paths das diapositivas completo (Para imprimir na diapositiva estática)
      @direcionFicheiroAnterior = @pathCompleto + @nomeAnterior + @extension
      @direcionFicheiroActual = @pathCompleto + @nomeActual + @extension
      @direcionFicheiroPrimeiro = @pathCompleto + @nomePrimeira + @extension

      #O ficheiro anterior apuntará ó ficheiro actual, en lugar de apuntar ó primeiro (para facer o círculo antes).
      #Elimínase a última línea do ficheiro (etiqueta meta-tag refresh)
        #Cárganse as liñas
        linas = IO.readlines(@nomeFicheiroAnterior)
        #Elimínanse as últimas 9 liñas (script redirección)
        var = 1
        while var < 10
          linas.delete_at(linas.length-1)
          var += 1
        end
        #Ábrese o ficheiro e escríbense todas as liñas (menos a eliminada)
        File.open(@nomeFicheiroAnterior, 'w') do |f|
          linas.each{ |linea| f.puts(linea) }
        end
        #Contén vídeo a diapositiva?
        eVideo = false
        @diapositivaAnterior.campos_formatos_subformatos_diapositivas.each do |cfsd|
          @campo = Campo.find(cfsd.campos_formatos_subformatos_campos_formatos_campo_id)
          if
            @campo.tipo == 'Vídeo'
            eVideo = true
            break
          end
        end

        #Ábrese o ficheiro para engadir o novo apuntamento
        File.open(@nomeFicheiroAnterior, 'a+') do |f|
          if eVideo == true
            f.puts("<script type=\"text/javascript\">\n\t" +
                        "$(\"#video\").bind(\"ended\", function() {\n\t\t" +
                          "window.location.replace(\"" + @direcionFicheiroActual + "\");\n\t" +
                        "});\n\n\t" +
                        "</script>\n\n\n\n")
          else
            f.puts("<script type=\"text/javascript\">\n\t" +
                        "function redirectLink() {\n\t\t" +
                          "window.location.replace(\"" + @direcionFicheiroActual + "\");\n\t" +
                        "}\n\n\t" +

                        "setTimeout(function () {\n\t\t" +
                          "redirectLink();\n\t" +
                        "}, " + @rexistroAnterior.factorTempo.to_i.to_s + "000);\n" +
                        "</script>")
          end
        end
      #O ficheiro actual apuntará ó primeiro rexistro
      outFile = File.open(@nomeFicheiroActual, "a+")
      #Contén vídeo a diapositiva?
        eVideo = false
        @diapositiva.campos_formatos_subformatos_diapositivas.each do |cfsd|
          @campo = Campo.find(cfsd.campos_formatos_subformatos_campos_formatos_campo_id)
          if
            @campo.tipo == 'Vídeo'
            eVideo = true
            break
          end
        end
        if eVideo == true
            outFile.puts("<script type=\"text/javascript\">\n\t" +
                        "$(\"#video\").bind(\"ended\", function() {\n\t\t" +
                          "window.location.replace(\"" + @direcionFicheiroPrimeiro + "\");\n\t" +
                        "});\n\n\t" +
                        "</script>\n\n\n\n")
          else
            outFile.puts("<script type=\"text/javascript\">\n\t" +
                      "function redirectLink() {\n\t\t" +
                        "window.location.replace(\"" + @direcionFicheiroPrimeiro + "\");\n\t" +
                      "}\n\n\t" +

                      "setTimeout(function () {\n\t\t" +
                        "redirectLink();\n\t" +
                      "}, " + @rexistroActual.factorTempo.to_i.to_s + "000);\n" +
                      "</script>")
        end
      outFile.close
    else
      #Copiar diapositiva á carpeta da lista
      FileUtils.cp "public/contidos/#{params[:diapositiva]}.html", "public/listas/#{@listareproducion.id}"

      #A url de comezo será a dirección da primeira diapositiva da lista
      @listareproducion.update_attributes!(:urlComezo => "public/listas/#{@listareproducion.id}/#{params[:diapositiva]}.html")

      #Engádese a meta-tag refresh para logo ir cambiándoa con cada diapositiva nova.

app/views/diapositivas_listareproducions/edit.html.erb
<div id="enlaces">
  <%= link_to 'Volver á lista de reproducion', edit_listareproducion_path(@listareproducion)%>
</div>

<div id="paxina">
  <h2> Datos </h2>
  <div id="datos">
    <p><b>Lista de reprodución: </b> <%= @listareproducion.nome %> </p>
    <p><b>Diapositiva: </b> <%= @diapositiva.nome %></p>
    <%= form_tag diapositivas_listareproducion_path(@rexistroActual), :method => :put do%>
      <%= hidden_field_tag :accion, 'modificar' %>
      <%= label_tag 'Factor Tempo' %>
      <%= text_field_tag 'factorTempo', @rexistroActual.factorTempo %>
      <br /><br />
      <%= submit_tag 'Actualizar' %>
    <% end %>
  </div>
</div>

app/views/diapositivas_listareproducions/new.html.erb
<div id="enlaces">
  <%= link_to 'Volver á lista de reprodución', listareproducion_path(@listareproducion) %>
  <%= link_to 'Volver ó listado', listareproducions_path %>
</div>

<div id="paxina">

  <h2> Diapositivas contidas </h2>
  <div id="datos">
    <% if @listareproducion.diapositivas.empty? %>
      <p> A lista de reprodución non contén diapositivas </p>
    <%  else %>
      <table id="tabla">
        <tr>
          <th>Id</th>
          <th>Nome</th>
          <th>Formato</th>
          <th>Dispositivo</th>
          <th>Estilo</th>
          <th>Url</th>
          <th>Detalles</th>
          <th>Orde</th>
          <th>Factor Tempo</th>
        </tr>
        <% @listareproducion_diapositivas.zip @listareproducion_rexistros %>
        <% @listareproducion_diapositivas.zip @listareproducion_formatos %>
        <% @listareproducion_diapositivas.zip(@listareproducion_rexistros, @listareproducion_formatos).each do |diapositiva,rexistro,formato| %>
        <tr>
          <td><%= diapositiva.id %></td>
          <td><%= diapositiva.nome %></td>
          <td><%= formato.nome %></td>
          <td><%= @dispositivo.relacionAspectoHorizontal %>:<%= @dispositivo.relacionAspectoVertical %></td>
          <td><%= diapositiva.estilo.nome %></td>
          <td><%= link_to diapositiva.url,  diapositiva.url, :target => '_blank' %></td>
          <td>
            <%= link_to 'Amosar', diapositiva_path(diapositiva) %>
            <%= image_tag 'amosar3.png', :size => '20x20', :style => 'vertical-align: bottom;' %>
          </td>
          <td><%= rexistro.orde %></td>
          <td><%= rexistro.factorTempo %></td>
        </tr>
        <% end %>
      </table>
    <% end %>
  </div>

  <h2> Ingresar diapositiva </h2>
    <div id="datos">

      <% if @diapositivas.empty? %>
        <p> Non existen diapositivas para poder engadir.</p>
      <% else %>
        <table id="tabla">
            <tr>
              <th>Id</th>
              <th>Nome</th>
              <th>Formato</th>
              <th>Dispositivo</th>
              <th>Estilo</th>
              <th>Url</th>
              <th>Detalles</th>
            </tr>
            <% @diapositivas.zip @diapositivas_formatos %>
            <% @diapositivas.zip(@diapositivas_formatos).each_with_index do |(diapositiva,formato),i| %>
            <% if !@dispositivos.nil?%>
              <% @dispositivo = @dispositivos[i] %>
            <% end %>
            <tr>
              <td><%= diapositiva.id %></td>
              <td><%= diapositiva.nome %></td>
              <td><%= formato.nome %></td>
              <td><%= @dispositivo.relacionAspectoHorizontal %>:<%= @dispositivo.relacionAspectoVertical %></td>
              <td><%= diapositiva.estilo.nome %></td>
              <td><%= link_to diapositiva.url,  diapositiva.url, :target => '_blank' %></td>
              <td>
                <%= link_to 'Amosar', diapositiva_path(diapositiva) %>
                <%= image_tag 'amosar3.png', :size => '20x20', :style => 'vertical-align: bottom;' %>
              </td>
            </tr>
            <% end %>
          </table>
        
        <%= form_tag diapositivas_listareproducions_path do%>
         <h3> Escolla unha diapositiva </h3>
            <%= label_tag 'Id' %>
            <%= select_tag :diapositiva, options_for_select(@opcionsSelect) %>
            <%= label_tag 'Factor tempo' %>
            <%= text_field_tag :factorTempoDiapositiva, '', :size => 4 %>
            <%= hidden_field_tag :id, @listareproducion.id %>
            <br /><br />
            <%= submit_tag 'Engadir diapositiva' %>
          <% end %>
      </div>
   <% end %>
</div>