config/routes.rb
TFG::Application.routes.draw do

  resources :dispositivofisicos

  resources :parametros

  resources :estilos

  resources :listareproducions

  resources :dispositivoloxicos

  resources :subformatos

  resources :diapositivas

  resources :campos

  resources :formatos

  resources :diapositivas_listareproducions

  resources :uploads
  
  match "/diapositivas_listareproducions/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/listareproducions/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/listareproducions/:id/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/diapositivas/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/diapositivas/:id/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")

  match "public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")

  match "/listareproducions/public/listas/:lista/:diapositiva" => redirect("/listas/%{lista}/%{diapositiva}")
  match "/listareproducions/:id/public/listas/:lista/:diapositiva" => redirect("/listas/%{lista}/%{diapositiva}")
  match "/public/listas/:lista/:diapositiva" => redirect("/listas/%{lista}/%{diapositiva}")

  match "dispositivofisicos/public/dispositivos/:dispositivo/inicio.html" => redirect("/dispositivos/%{dispositivo}/inicio.html")
  match "/dispositivos/:dispositivo/public/listas/:lista/:diapositiva" => redirect("/listas/%{lista}/%{diapositiva}")
  
  post 'listareproducions/:id/edit', :controller => 'listareproducions', :action => 'edit', :id => '%{id}'
  post 'diapositivas/uploadFile'
  post 'uploads/uploadFile'

  post 'campos/desvincular'

end

app/models/listareproducion.rb
class Listareproducion < ActiveRecord::Base
   attr_accessible :id, :factorTempo, :urlComezo, :nome
   has_many :diapositivas_listareproducions
   has_many :diapositivas, :through => :diapositivas_listareproducions
   has_many :dispositivoloxicos
end

app/controllers/listareproducions_controller.rb
# encoding: utf-8

class ListareproducionsController < ApplicationController
  # GET /listareproducions
  # GET /listareproducions.json
  def index
    #Recóllense todas as listas de reprodución
    @listareproducions = Listareproducion.all
    #Recóllense todos os dispositivos das listas
    @dispositivos = Array.new

    #Búsqueda do tipo de dispositivo para o que foi deseñada cada lista
    @listareproducions.each do |listareproducion|
    #Cóllese a primeira diapositiva e consúltase o dispositivo ó que pertence o subformato de esta
    @listareproducion_diapositivas = DiapositivasListareproducion.find_all_by_listareproducion_id(listareproducion.id)
    if !@listareproducion_diapositivas.empty?
      @diapositiva = Diapositiva.find(@listareproducion_diapositivas[0].diapositiva_id)
      @diapositiva_formato = @diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_campos_formatos_formato_id
      @diapositiva_subformato = @diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_subformato_id
      @dispositivo = Subformato.find(@diapositiva_subformato).dispositivoloxico
      @dispositivos << @dispositivo
    end
    end
  end

  # GET /listareproducions/1
  # GET /listareproducions/1.json
  def show
    #Lista de reprodución
    @listareproducion = Listareproducion.find(params[:id])
    #Diapositivas da lista
    @listareproducion_diapositivas = Array.new
    #Formatos das diapositivas da lista
    @listareproducion_formatos = Array.new
    @listareproducion_rexistros = DiapositivasListareproducion.find_all_by_listareproducion_id(@listareproducion.id, :order => "orde")

    @listareproducion_rexistros.each do |rexistro|
      @listareproducion_diapositivas << Diapositiva.find(rexistro.diapositiva_id)
      @listareproducion_formatos << Formato.find(Diapositiva.find(rexistro.diapositiva_id).campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_campos_formatos_formato_id)
    end

    #Búsqueda do tipo de dispositivo para o que foi deseñada, se xa ten
    if !@listareproducion_diapositivas.empty?
      @diapositiva = Diapositiva.find(@listareproducion_diapositivas[0].id)
      @diapositiva_formato = @diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_campos_formatos_formato_id
      @diapositiva_subformato = @diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_subformato_id
      @dispositivo = Subformato.find(@diapositiva_subformato).dispositivoloxico
    end
   
  end

  # GET /listareproducions/new
  # GET /listareproducions/new.json
  def new
    #Nova lista
    @listareproducion = Listareproducion.new
    #Recóllense todos os dispositivos lóxicos
    @dispositivoloxicos = Dispositivoloxico.all
    if params[:dispositivo]
      @dispositivo = Dispositivoloxico.find(params[:dispositivo])
      #Escoller as diapositivas adaptadas a ese dispositivo
        #Primeiro recóllense os subformatos creados para dito dispositivo
        @subformatos = Subformato.find_all_by_dispositivoloxico_id(@dispositivo.id)
        #Extráense as entradas da táboa campos - formatos - subformatos - diapositivas que indiquen que as diapositivas son dos subformatos escollidos
        @diapositivas = Array.new
        #Extráense os formatos das diapositivas
        @diapositivas_formatos = Array.new
        #Gárdanse os ids das diapositivas para ser opcións do select na vista
        @opcionsSelect = Array.new
        @subformatos.each do |subformato|
          #Só se necesita o id da diapositiva, e con unha vez resulta suficiente
          @rexistros = CamposFormatosSubformatosDiapositiva.where(:campos_formatos_subformatos_subformato_id => subformato.id).select(:diapositiva_id).uniq
          @rexistros.each do |rexistro|
            #Recóllense os datos da diapositiva e introdúcese nun array
            @diapositiva = Diapositiva.find(rexistro.diapositiva_id)
            @diapositivas << @diapositiva
            @diapositivas_formatos << Formato.find(@diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_campos_formatos_formato_id)
            @opcionsSelect << @diapositiva.id
          end
        end
    end
  end

  # GET /listareproducions/1/edit
  def edit
    #Lista de reprodución
    @listareproducion = Listareproducion.find(params[:id])
    #Diapositivas da lista
    @listareproducion_diapositivas = Array.new
    #Formatos das diapositivas da lista
    @listareproducion_formatos = Array.new
    @listareproducion_rexistros = DiapositivasListareproducion.find_all_by_listareproducion_id(@listareproducion.id, :order => "orde")

    @listareproducion_rexistros.each do |rexistro|
      @listareproducion_diapositivas << Diapositiva.find(rexistro.diapositiva_id)
      @listareproducion_formatos << Formato.find(Diapositiva.find(rexistro.diapositiva_id).campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_campos_formatos_formato_id)
    end

    #Búsqueda do tipo de dispositivo para o que foi deseñada, se xa ten diapositivas
    if !@listareproducion_diapositivas.empty?
      @diapositiva = Diapositiva.find(@listareproducion_diapositivas[0].id)
      @diapositiva_formato = @diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_campos_formatos_formato_id
      @diapositiva_subformato = @diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_subformato_id
      @dispositivo = Subformato.find(@diapositiva_subformato).dispositivoloxico
    end
  end

  # POST /listareproducions
  # POST /listareproducions.json
  def create
    @listareproducion = Listareproducion.create!(:nome => params[:nome])
    DiapositivasListareproducion.create!(:diapositiva_id => params[:diapositiva], :listareproducion_id => @listareproducion.id, :factorTempo => params[:factorTempoDiapositiva], :orde => '1')

    #Crear carpeta para a lista
    Dir.mkdir"public/listas/#{@listareproducion.id}"
    #Copiar diapositiva á carpeta da lista
    FileUtils.cp "public/contidos/#{params[:diapositiva]}.html", "public/listas/#{@listareproducion.id}"

    #A url de comezo será a dirección da primeira diapositiva da lista
    @listareproducion.update_attributes!(:urlComezo => "public/listas/#{@listareproducion.id}/#{params[:diapositiva]}.html")

    #Engádese a meta-tag refresh para logo ir cambiándoa con cada diapositiva nova.
      #Configuración do ficheiro
      @path = "public/listas/#{@listareproducion.id}/"
      @extension = ".html"

      #Nome da diapositiva
      @nome = params[:diapositiva]

      #Paths da diapositiva
      @nomeFicheiro = @path + @nome + @extension

      #Apertura de ficheiro para engadir etiqueta refresh, por agora sen apuntar a ningunha
      outFile = File.open(@nomeFicheiro, "a+")
      redireccion = "<script type=\"text/javascript\">\n\t" + 
                      "function redirectLink() {\n\t\t" +
                        "window.location.replace();\n\t" +
                      "}\n\n\t" +

                      "setTimeout(function () {\n\t\t" +
                        "redirectLink();\n\t" +
                      "}, -1);\n" +
                      "</script>"
      outFile.puts(redireccion)
      outFile.close
    flash[:notificacion] = "Lista de reprodución creada con éxito."
    redirect_to :controller => "listareproducions", :action => :edit, :id => @listareproducion.id
  end

  # PUT /listareproducions/1
  # PUT /listareproducions/1.json
  def update
    @listareproducion = Listareproducion.find(params[:id])
    @listareproducion.update_attributes!(:nome => params[:nome])
    flash[:notificacion] = "Lista de reprodución actualizada con éxito."
    redirect_to listareproducion_path(@listareproducion)
  end

  # DELETE /listareproducions/1
  # DELETE /listareproducions/1.json
  def destroy
    #Búscase a lista
    @listareproducion = Listareproducion.find(params[:id])
    #Gárdase o id
    @id = @listareproducion.id
    
    #Eliminar os rexistros da relación diapositivas - listas de reprodución
    @rexistros = DiapositivasListareproducion.find_all_by_listareproducion_id(@id)
    @rexistros.each do |rexistro|
      rexistro.destroy
    end
    

    #Eliminar ficheiros estáticos da carpeta public
    FileUtils.rm_rf("public/listas/#{@id}/")

    #Elimínase a lista
    @listareproducion.destroy

    flash[:notificacion] = "Lista de reproducion eliminada con éxito."
    redirect_to listareproducions_path
  end
end

app/helpers/listareproducions_helper.rb
module ListareproducionsHelper
end

app/views/listareproducions/_form.html.erb
<%= form_for(@listareproducion) do |f| %>
  <% if @listareproducion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listareproducion.errors.count, "error") %> prohibited this listareproducion from being saved:</h2>

      <ul>
      <% @listareproducion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listareproducions/edit.html.erb
<div id="enlaces">
  <%= link_to 'Amosar', @listareproducion %>
  <%= link_to 'Volver á listaxe', listareproducions_path %>
</div>

<% if flash[:notificacion] %>
  <div id="notificacion"><%= flash[:notificacion]%></div>
<% end %>

<div id="paxina">

  <h2> Datos </h2>
  <div id="datos">
    <%= form_tag listareproducion_path(@listareproducion), :method => :put do%>
      <%= label_tag 'Nome' %>
      <%= text_field_tag :nome, @listareproducion.nome %>
      <p><b>Url comezo: </b><%= link_to @listareproducion.urlComezo, @listareproducion.urlComezo, :target => '_blank' %></p>
      <%= submit_tag "Actualizar datos" %>
    <% end %>
  </div>

  <h2> Diapositivas contidas </h2>
  <div id="datos">
    <% if @listareproducion.diapositivas.empty? %>
      <p> A lista de reprodución non contén diapositivas </p>
    <%  else %>
      <table id="tabla">
        <tr>
          <th>Nome</th>
          <th>Formato</th>
          <th>Dispositivo</th>
          <th>Estilo</th>
          <th>Url</th>
          <th>Detalles</th>
          <th>Orde</th>
          <th>Factor tempo</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        <% @listareproducion_diapositivas.zip @listareproducion_rexistros %>
        <% @listareproducion_diapositivas.zip @listareproducion_formatos %>
        <% @listareproducion_diapositivas.zip(@listareproducion_rexistros,@listareproducion_formatos).each_with_index do |(diapositiva,rexistro,formato),i| %>
        <tr>
          <td><%= diapositiva.nome %></td>
          <td><%= formato.nome %></td>
          <td><%= @dispositivo.relacionAspectoHorizontal %>:<%= @dispositivo.relacionAspectoVertical %></td>
          <td><%= diapositiva.estilo.nome %></td>
          <td><%= link_to diapositiva.url,  diapositiva.url, :target => '_blank' %></td>
          <td>
            <%= link_to 'Amosar', diapositiva_path(diapositiva) %>
            <%= image_tag 'amosar3.png', :size => '20x20', :style => 'vertical-align: bottom;' %>
          </td>
          <td><%= rexistro.orde %></td>
          <td><%= rexistro.factorTempo %></td>
          <td>
            <% if @listareproducion_diapositivas.length > 1 %>
              <% if i == 0 %>
                <%= form_tag diapositivas_listareproducion_path(rexistro), :method => :put do%>
                  <%= hidden_field_tag :accion, 'baixar' %>
                  <%= image_submit_tag 'abajo.gif', :id => 'imaxeBaixar' %>
                <% end %>
              <% elsif i == @listareproducion_diapositivas.length-1 %>
                <%= form_tag diapositivas_listareproducion_path(rexistro), :method => :put do%>
                  <%= hidden_field_tag :accion, 'subir' %>
                  <%= image_submit_tag 'arriba.gif', :id => 'imaxeSubir'%>
                <% end %>
              <% else %>
                <%= form_tag diapositivas_listareproducion_path(rexistro), :method => :put do%>
                    <%= hidden_field_tag :accion, 'subir' %>
                    <%= image_submit_tag 'arriba.gif', :id => 'imaxeSubir'%>
                <% end %>
                <%= form_tag diapositivas_listareproducion_path(rexistro), :method => :put do%>
                    <%= hidden_field_tag :accion, 'baixar' %>
                    <%= image_submit_tag 'abajo.gif', :id => 'imaxeBaixar' %>
                <% end %>
              <% end %>
            <% end %>
          </td>
          <td>
            <%= link_to 'Editar', edit_diapositivas_listareproducion_path(rexistro) %>
            <%= image_tag 'editar3.png', :size => '20x20', :style => 'vertical-align: bottom;' %>
          </td>
          <td>
            <%= link_to 'Eliminar', rexistro, method: :delete, data: { confirm: 'Seguro?'} %>
            <%= image_tag 'eliminar3.png', :size => '20x20', :style => 'vertical-align: bottom;' %>
          </td>
        </tr>
        <% end %>
      </table>
    <% end %>
    <p>
      <%= link_to 'Engadir diapositiva á lista', new_diapositivas_listareproducion_path(:lista => @listareproducion.id)%>
    </p>
  </div>
</div>

app/views/listareproducions/index.html.erb
<div id="enlaces">
  <%= link_to 'Nova lista de reprodución', new_listareproducion_path %>
  <%= link_to 'Volver ó inicio', '/' %>
</div>

<% if flash[:notificacion] %>
  <div id="notificacion"><%= flash[:notificacion]%></div>
<% end %>

<div id="paxina">

  <h2> Listaxe </h2>
  <div id="datos">
  <% if @listareproducions.empty? %>
      <p> Non existen listas de reprodución! </p>
  <% else %>
    <table id="tabla">
      <tr>
        <th>Nome</th>
        <th>Tipo dispositivo</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    <% @listareproducions.zip @dispositivos %>
    <% @listareproducions.zip(@dispositivos).each do |listareproducion,dispositivo| %>
      <tr>
        <td><%= listareproducion.nome %></td>
        <td><%  if !dispositivo.nil? %>
              <%= dispositivo.relacionAspectoHorizontal %>:<%= dispositivo.relacionAspectoVertical %>
            <% else %>
              Sen asignar
            <% end %>
        </td>
        <td>
          <%= link_to 'Amosar', listareproducion %>
          <%= image_tag 'amosar3.png', :size => '20x20', :style => 'vertical-align: bottom;' %>
        </td>
        <td>
          <%= link_to 'Editar', edit_listareproducion_path(listareproducion) %>
          <%= image_tag 'editar3.png', :size => '20x20', :style => 'vertical-align: bottom;' %>
        </td>
        <td>
          <%= link_to 'Eliminar', listareproducion, method: :delete, data: { confirm: 'Seguro?' } %>
          <%= image_tag 'eliminar3.png', :size => '20x20', :style => 'vertical-align: bottom;' %>
        </td>
      </tr>
    <% end %>
    </table>
  <% end %>
  </div>
</div>

app/views/listareproducions/new.html.erb
<div id="enlaces">
  <%= link_to 'Volver á listaxe', listareproducions_path %>
</div>

<div id="paxina">

  <% if !params[:dispositivo] %>
  <h2> Dispositivos dispoñibles </h2>
  <div id="datos">
    <p> Selecione o dispositivo para o que se creará a lista de reprodución.</p>
    <%= form_tag new_listareproducion_path, :method => :get do%>
    <ul>
      <% @dispositivoloxicos.each do |dispositivo| %>
        <li>
        <%= radio_button_tag 'dispositivo', dispositivo.id %>
        (<%= dispositivo.relacionAspectoHorizontal %>:<%= dispositivo.relacionAspectoVertical %>)
        </li>
      <% end %>
    </ul>
      <%= submit_tag "Selecionar"%>
    <% end %>
  </div>

  <% else %>
    <h2> Diapositivas posibles </h2>
    <div id ="datos">
    <% if @diapositivas.empty? %>
        <p> Non existen diapositivas para dito dispositivo.</p>
    <% else %>
      <table id="tabla">
            <tr>
              <th>Id</th>
              <th>Nome</th>
              <th>Formato</th>
              <th>Dispositivo</th>
              <th>Estilo</th>
              <th>Url</th>
              <th></th>
            </tr>
            <% @diapositivas.zip @diapositivas_formatos %>
            <% @diapositivas.zip(@diapositivas_formatos).each do |diapositiva,formato| %>
            <tr>
              <td><%= diapositiva.id %> </td>
              <td><%= diapositiva.nome %></td>
              <td><%= formato.nome %></td>
              <td><%= @dispositivo.relacionAspectoHorizontal %>:<%= @dispositivo.relacionAspectoVertical %></td>
              <td><%= diapositiva.estilo.nome %></td>
              <td><%= link_to diapositiva.url,  diapositiva.url, :target => '_blank' %></td>
              <td><%= link_to 'Amosar', diapositiva_path(diapositiva) %></td>
            </tr>
            <% end %>
          </table>
      </div>
  
      <h2> Creando a lista </h2>
        <div id="datos">
          <%= form_tag listareproducions_path do%>
          <h3> Datos </h3>
            <%= label_tag 'Nome' %>
            <%= text_field_tag :nome, '' %>
            <h3> Escolla a primeira diapositiva </h3>
              <%= label_tag 'Id' %>
              <%= select_tag :diapositiva, options_for_select(@opcionsSelect) %>
              <%= label_tag 'Factor tempo' %>
              <%= text_field_tag :factorTempoDiapositiva, '', :size => 4 %>
              <%= hidden_field_tag :id, @listareproducion.id %>
              <br /><br />
              <%= submit_tag 'Engadir diapositiva' %>
            <% end %>
        </div>
      <% end %>
  <% end %>
</div>

app/views/listareproducions/show.html.erb
<div id="enlaces">
  <%= link_to 'Editar', edit_listareproducion_path(@listareproducion) %>
  <%= link_to 'Volver á listaxe', listareproducions_path %>
</div>

<% if flash[:notificacion] %>
  <div id="notificacion"><%= flash[:notificacion]%></div>
<% end %>

<div id="paxina">
  <h2> Datos </h2>
  <div id="datos">
    <p><b>Nome: </b><%= @listareproducion.nome %></p>
    <p><b>Url comezo: </b><%= link_to @listareproducion.urlComezo, @listareproducion.urlComezo %></p>
  </div>

  <h2> Diapositivas contidas </h2>
  <div id="datos">
    <% if @listareproducion.diapositivas.empty? %>
      <p> A lista de reprodución non contén diapositivas </p>
    <%  else %>
      <table id="tabla">
        <tr>
          <th>Id</th>
          <th>Formato</th>
          <th>Dispositivo</th>
          <th>Estilo</th>
          <th>Url</th>
          <th>Detalles</th>
          <th>Orde</th>
          <th>Factor tempo</th>
        </tr>
        <% @listareproducion_diapositivas.zip @listareproducion_rexistros %>
        <% @listareproducion_formatos.zip @listareproducion_formatos  %>
        <% @listareproducion_diapositivas.zip(@listareproducion_rexistros, @listareproducion_formatos).each do |diapositiva,rexistro,formato| %>
        <tr>
          <td><%= diapositiva.nome %></td>
          <td><%= formato.nome %></td>
          <td><%= @dispositivo.relacionAspectoHorizontal %>:<%= @dispositivo.relacionAspectoVertical %></td>
          <td><%= diapositiva.estilo.nome %></td>
          <td><%= link_to diapositiva.url,  diapositiva.url, :target => '_blank' %></td>
          <td><%= link_to 'Amosar', diapositiva_path(diapositiva) %></td>
          <td><%= rexistro.orde %></td>
          <td><%= rexistro.factorTempo %></td>
        </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>