config/routes.rb
TFG::Application.routes.draw do

  resources :dispositivofisicos

  resources :parametros

  resources :estilos

  resources :listareproducions

  resources :dispositivoloxicos

  resources :subformatos

  resources :diapositivas

  resources :campos

  resources :formatos

  resources :diapositivas_listareproducions

  resources :uploads
  
  match "/diapositivas_listareproducions/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/listareproducions/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/listareproducions/:id/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/diapositivas/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/diapositivas/:id/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")

  match "public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")

  match "/listareproducions/public/listas/:lista/:diapositiva" => redirect("/listas/%{lista}/%{diapositiva}")
  match "/listareproducions/:id/public/listas/:lista/:diapositiva" => redirect("/listas/%{lista}/%{diapositiva}")
  match "/public/listas/:lista/:diapositiva" => redirect("/listas/%{lista}/%{diapositiva}")

  match "dispositivofisicos/public/dispositivos/:dispositivo/inicio.html" => redirect("/dispositivos/%{dispositivo}/inicio.html")
  match "/dispositivos/:dispositivo/public/listas/:lista/:diapositiva" => redirect("/listas/%{lista}/%{diapositiva}")
  
  post 'listareproducions/:id/edit', :controller => 'listareproducions', :action => 'edit', :id => '%{id}'
  post 'diapositivas/uploadFile'
  post 'uploads/uploadFile'

  post 'campos/desvincular'

end

app/models/diapositiva.rb
class Diapositiva < ActiveRecord::Base
   attr_accessible :id, :url, :estilo_id, :nome
   belongs_to :estilo
   has_many :campos_formatos_subformatos_diapositivas
   has_many :campos_formatos_subformatos, :through => :campos_formatos_subformatos_diapositivas
   has_many :diapositivas_listareproducions
   has_many :listareproducions, :through => :diapositivas_listareproducions
end

app/controllers/diapositivas_controller.rb
# encoding: utf-8
class DiapositivasController < ApplicationController
  # GET /diapositivas
  # GET /diapositivas.json
  def index
    #Cada diapositiva
    @diapositivas = Diapositiva.all
    #Almacenamento dos dispositivos
    @diapositivas_dispositivo = Array.new
    #Almacenamento dos formatos das diapositivas
    @diapositivas_formato = Array.new
    #Recóllese a información de cada diapositiva
    @diapositivas.each do |diapositiva|
      #Dispositivo para o que está deseñado. Acceso por diapositiva -> Subformato -> Dispositivo
      @diapositiva_subformato = diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_subformato_id
      @dispositivo = Subformato.find(@diapositiva_subformato).dispositivoloxico
      @diapositivas_dispositivo << @dispositivo.relacionAspectoHorizontal.to_s + ":" + @dispositivo.relacionAspectoVertical.to_s
      #Formato da diapositiva
      @diapositivas_formato << Formato.find(diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_campos_formatos_formato_id)
    end
  end

  # GET /diapositivas/1
  # GET /diapositivas/1.json
  def show
    @diapositiva = Diapositiva.find(params[:id])
    @diapositiva_formato = Formato.find(@diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_campos_formatos_formato_id)
    @diapositiva_subformato = @diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_subformato_id
    @dispositivo = Subformato.find(@diapositiva_subformato).dispositivoloxico
    @diapositiva_dispositivo = @dispositivo.relacionAspectoHorizontal.to_s + ":" + @dispositivo.relacionAspectoVertical.to_s

    #Campos da diapositiva
    @diapositiva_campos = Array.new
    @diapositiva.campos_formatos_subformatos_diapositivas.each do |rexistro|
      @diapositiva_campos << Campo.find(rexistro.campos_formatos_subformatos_campos_formatos_campo_id)
    end
  end

  # GET /diapositivas/new
  # GET /diapositivas/new.json
  def new
    @diapositiva = Diapositiva.new
    @formatos = Formato.all
    @subformatos = Subformato.all
    @dispositivosloxicos = Dispositivoloxico.all
    #Si xa escollemos un formato, búscase para recoller os seus datos
    if params[:idFormato]
      @estilos = Estilo.all
      @formato = Formato.find(params[:idFormato])
      #Rexistros dos campos que contén
      @rexistros = CamposFormato.find_all_by_formato_id(@formato.id)
      #Datos que serán impresos
      @imprimirDispositivos = ""
      @imprimirSubformatos = ""
      @subformatosEscollidos = params[:subformato]
      @formato.subformatos.each_with_index do |subformato,i|
        @subformatosEscollidos.each do |subformatoEscollido|
          if subformato.id == subformatoEscollido.to_i
            @imprimirDispositivos = @imprimirDispositivos + subformato.dispositivoloxico.relacionAspectoHorizontal.to_s + ":" + subformato.dispositivoloxico.relacionAspectoVertical.to_s + " "
            @imprimirSubformatos = @imprimirSubformatos + subformato.id.to_s + " "
          end
        end
      end
    end

    #Imaxes en directorio
    @imaxes = Dir.glob("app/assets/images/usuario/*")
    #Vídeos en directorio
    @videos = Dir.glob("public/videos/*")

  end

  # GET /diapositivas/1/edit
  def edit
    @diapositiva = Diapositiva.find(params[:id])
    @diapositiva_formato = Formato.find(@diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_campos_formatos_formato_id)
    @diapositiva_subformato = @diapositiva.campos_formatos_subformatos_diapositivas[0].campos_formatos_subformatos_subformato_id
    @dispositivo = Subformato.find(@diapositiva_subformato).dispositivoloxico
    @diapositiva_dispositivo = @dispositivo.relacionAspectoHorizontal.to_s + ":" + @dispositivo.relacionAspectoVertical.to_s

    #Campos da diapositiva
    @diapositiva_campos = Array.new
    @diapositiva.campos_formatos_subformatos_diapositivas.each do |registro|
      @diapositiva_campos << Campo.find(registro.campos_formatos_subformatos_campos_formatos_campo_id)
    end

    #Rexistros dos campos que contén
    @rexistrosCamposFormato = CamposFormato.find_all_by_formato_id(@diapositiva_formato)
    
    #Estilos existentes
    @estilos = Estilo.all
    #Imaxes en directorio
    @imaxes = Dir.glob("app/assets/images/usuario/*")
    #Vídeos en directorio
    @videos = Dir.glob("public/videos/*")

  end

  # POST /diapositivas
  # POST /diapositivas.json
  def create
    #Configuración do ficheiro
    @path = "public/contidos/"
    @extension = ".html"

    #Mensaxe para imprimir
    @diapositivasCreadas = Array.new

    #Recóllense os ids dos subformatos escollidos
    @subformatos = params[:subformatos]
    #Conocemos polo tanto, o formato
    @formato = Subformato.find(@subformatos[0]).formato.id
    #Recóllense os ids dos rexistros
    @idsRexistros = params[:idRexistro]
    #Recóllense os valores dos campos
    @valores = params[:valor]
    #Recóllese o estilo
    @idEstilo = params[:estilo]
    #Búsqueda do estilo
    @estilo = Estilo.find(@idEstilo[0])
    

    @subformatos.each do |subformato|
      #Para cada subformato, crease unha diapositiva
      @diapositiva = Diapositiva.create(:nome => params[:nome])
      #Asignación do estilo
      @diapositiva.update_attributes!(:estilo_id => @estilo.id)
      #Creouse unha diapositiva, polo tanto almaceno o seu id, para logo informar
      @diapositivasCreadas << @diapositiva.id
      #O nome da diapositiva será o id xerado
      @nombre = @diapositiva.id.to_s
      #Configúrase o nome do ficheiro HTML a crear
      @nombreFichero = @path + @nombre + @extension
      outFile = File.new(@nombreFichero, "w")

      #AQUÍ VAI A PLANTILLA HTML
      plantilla()
      outFile.puts(@plantilla)

      #Plantillas para o estilo, o contido html e o javascript
      @style = "<style type=\"text/css\">\n\t"
      @script = "<script type=\"text/javascript\">\n\t"
      @html = ""

      #Créase o css para o fondo, segundo as propiedades escollidas
      @style = @style + "body{\n"

      #Cor de fondo
      if !@estilo.background_color.nil? && @estilo.background_color.length > 0
        @style = @style + "\t\tbackground-color: " + @estilo.background_color + ";\n"
      end

      #Imaxe
      if !@estilo.background_image.nil? && @estilo.background_image.length > 0
        @style = @style + "\t\tbackground-image: url(\"" + @estilo.background_image + "\");\n"
        #Imaxe > Repetición
        if !@estilo.background_repeat.nil? && @estilo.background_repeat.length > 0
          case @estilo.background_repeat
            when 'Repetir X e Y'
              @background_repeat_css = "repeat"
            when 'Repetir X'
              @background_repeat_css = "repeat-x"
            when 'Repetir Y'
              @background_repeat_css = "repeat-y"
            when 'Non repetir'
              @background_repeat_css = 'no-repeat'
          end
          @style = @style + "\t\tbackground-repeat: " + @background_repeat_css + ";\n"
        end
        #Imaxe > Posición
        if !@estilo.background_position.nil? && @estilo.background_position.length > 0
          case @estilo.background_position
            when 'Esquerda Arriba'
              @background_position_css = "left top"
            when 'Esquerda Centro'
              @background_position_css = "left center"
            when 'Esquerda Abaixo'
              @background_position_css = "left bottom"
            when 'Dereita Arriba'
              @background_position_css = "right top"
            when 'Dereita Centro'
              @background_position_css = "right center"
            when 'Dereita Abaixo'
              @background_position_css = "right bottom"
            when 'Centro Arriba'
              @background_position_css = "center top"
            when 'Centro Centro'
              @background_position_css = "center center"
            when 'Centro Abaixo'
              @background_position_css = "center bottom"
            when 'Posicion X Posicion Y'
              @background_position_css = @estilo.background_position_x + "px " + @estilo.background_position_y + "px"
            when '%x %y'
              @background_position_css = @estilo.background_position_x + "% " + @estilo.background_position_y + "%"
          end
          @style = @style + "\t\tbackground-position: " + @background_position_css + ";\n"
        end
        #Imaxe > Tamaño
        if !@estilo.background_size.nil? && @estilo.background_size.length > 0
          case @estilo.background_size
          when 'Cover'
            @background_size_css = "cover"
          when 'Contain'
            @background_size_css = "contain"
          when 'X pixels Y pixels'
            @background_size_css = @estilo.background_size_x + "px " + @estilo.background_size_y + "px"
          when 'Pixels'
            @background_size_css = @estilo.background_size_val + "px"
          when '%x %y'
            @background_size_css = @estilo.background_size_x + "% " + @estilo.background_size_y + "%"
          when 'Porcentaxe'
            @background_size_css = @estilo.background_size_val + "%"
          end
          @style = @style + "\t\tbackground-size: " + @background_size_css + ";\n"
        end
      end
      @style = @style + "\t}\n\n"
      
      #Recórrense os campos e os seus valores
      @idsRexistros.zip @valores
      @idsRexistros.zip(@valores).each do |idRexistro,valor|
        #Búscase a entrada de campos_formatos_subformatos
        @datosCampo = CamposFormatosSubformato.find_by_campos_formato_id_and_subformato_id(idRexistro,subformato)
        #Búsqueda da información do campo
        @campo = Campo.find(@datosCampo.campos_formatos_campo_id)
        #Crease unha entrada para cada campo - formato - subformato - diapositiva

app/helpers/diapositivas_helper.rb
module DiapositivasHelper
end

app/views/diapositivas/_form.html.erb
<%= form_for(@diapositiva) do |f| %>
  <% if @diapositiva.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diapositiva.errors.count, "error") %> prohibited this diapositiva from being saved:</h2>

      <ul>
      <% @diapositiva.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diapositivas/edit.html.erb
<div id="enlaces">
  <%= link_to 'Amosar', @diapositiva %>
  <%= link_to 'Volver ó listado de diapositivas', diapositivas_path %>
</div>

<div id="paxina">

  <h2> Datos </h2>
  <div id="datos">
    <%= form_tag diapositiva_path(@diapositiva), :method => :put do %>
      <p><b>Nome: </b><br /><%= text_field_tag :nome, @diapositiva.nome %></p>
      <p><b>Url: </b> <%= link_to @diapositiva.url,  @diapositiva.url, :target => '_blank' %></p>
      <p><b>Diapositiva con formato: </b><%= @diapositiva_formato.nome %></p>
      <p><b>Diapositiva para dispositivo: </b><%= @diapositiva_dispositivo%></p>
      <%= hidden_field_tag :accion, 'datos' %>
      <%= submit_tag 'Actualizar datos' %>
    <% end %>
  </div>

  <h2> Contido </h2>
  <div id="datosConGaleria">
    <%= form_tag diapositiva_path(@diapositiva), :id =>'diapositivas', :method => :put do%>
      <!-- Estilo desexado -->
        <%= label_tag 'Estilo' %>
        <% if @estilos.empty? %>
          <p>Non existen estilos!</p>
        <% else %>
          <% @estilos.each do |estilo| %>
            <% if @diapositiva.estilo.nil? || @diapositiva.estilo.id != estilo.id %>
              <%= radio_button "estilo", "", estilo.id %> <%= estilo.nome %>
              <%= link_to 'Detalles', estilo_path(estilo), :target => '_blank' %>
              <%= image_tag 'amosar3.png', :size => '20x20', :style => 'vertical-align: top;' %>
              <br />
            <% else %>
              <%= radio_button "estilo", "", estilo.id, :checked => true %> <%= estilo.nome %>
              <%= link_to 'Detalles', estilo_path(estilo), :target => '_blank' %>
              <%= image_tag 'amosar3.png', :size => '20x20', :style => 'vertical-align: top;' %>
              <br />
            <% end %>
          <% end %>
        <% end %>

      <% @diapositiva.campos_formatos_subformatos_diapositivas.zip @diapositiva_campos %>
      <% @diapositiva.campos_formatos_subformatos_diapositivas.zip @rexistrosCamposFormato %>
      <% @diapositiva.campos_formatos_subformatos_diapositivas.zip(@diapositiva_campos,@rexistrosCamposFormato).each do |rexistro,campo,campoFormato| %>
        <%= label_tag campo.subtipo %>
        <% if campo.tipo == 'Imaxe' %>
          <%= image_tag rexistro.contido, :size => '160x120' %><br />
          <div id="selecionContido">
            <p id="cargarGaleria">
                Escoller da galería
                <%= image_tag 'galeria.png', :size => '20x20', :style => 'vertical-align: top;' %>
              </p>
            <div id="galeria">
              <%  @imaxes.each do |imaxe| %>
                <%= image_tag(imaxe.gsub("app/assets/images/", ""), :size => '100x100') %>
              <% end %>
            </div>
            <%= text_field_tag 'valor[]', rexistro.contido, :size => 50, :id => 'pathContido' %>
            <p id="explicacion">
              Tam&eacute;n pode facilitar unha ligaz&oacute;n externa.
            </p>
          </div>
        <% elsif campo.subtipo == 'Título' || campo.subtipo == 'Subtítulo' || campo.subtipo == 'Pé' %>
            <%= text_field_tag 'valor[]',rexistro.contido, :size => 50 %>
        <% elsif campo.subtipo == 'Resumo' || campo.subtipo == 'Descrición'%>
            <%= text_area_tag('valor[]', rexistro.contido, :size => "48x5", :resize => "horizontal")%>
        <% elsif campo.tipo = 'Video' %>
          <% if campo.subtipo == 'Embebido' %>
            <%= rexistro.contido.html_safe %><br />
            <%= text_area_tag('valor[]', rexistro.contido, :size => "48x5", :resize => "horizontal")%>
          <% else %>
            <%= video_tag(rexistro.contido, :controls => true) %></video>
            <div id="selecionContido">
            <p id="cargarGaleria">
                Escoller da galería
                <%= image_tag 'galeria.png', :size => '20x20', :style => 'vertical-align: top;' %>
              </p>
            <div id="galeria">
              <%  @videos.each do |video| %>
                    <%= video_tag(video.gsub("public/videos/", ""), :size => "200x200") %></video>
              <% end %>
            </div>
            <%= text_field_tag 'valor[]', rexistro.contido, :size => 50, :id => 'pathContido' %>
            <p id="explicacion">
              Tam&eacute;n pode facilitar unha ligaz&oacute;n externa.
            </p>
          </div>
          <% end %>
        <% end %> <!-- END if tipo campo -->
        <%= hidden_field_tag 'idRexistro[]', campoFormato.id %>
      <% end %> <!-- END campos -->
      <p>
        <%= submit_tag 'Actualizar contido' %>
      </p>
    <% end %> <!-- END form -->
  </div>
</div>

app/views/diapositivas/index.html.erb
<div id="enlaces">
  <%= link_to 'Nova diapositiva', new_diapositiva_path %>
  <%= link_to 'Volver ó inicio', "/" %>
</div>

<% if flash[:notificacion] %>
  <div id="notificacion"><%= flash[:notificacion]%></div>
<% end %>

<div id="paxina">
  <h2>Listado de diapositivas</h2>

  <div id="datos">
    <% if @diapositivas.empty? %>
     Non existen diapositivas!
    <% else %>
     <table id="tabla">
      <tr>
        <th>Nome</th>
        <th>Formato</th>
        <th>Dispositivo</th>
        <th>Estilo</th>
        <th>Url</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    <% @diapositivas.zip @diapositivas_dispositivo %>
    <% @diapositivas.zip @diapositivas_formato %>
    <% @diapositivas.zip(@diapositivas_dispositivo,@diapositivas_formato).each do |diapositiva,dispositivo,formato| %>
      <tr>
            <td><%= diapositiva.nome %></td>
            <td><%= formato.nome %></td>
            <td><%= dispositivo %></td>
            <td>
              <% if diapositiva.estilo.nil? %>
                Sen estilo definido
              <% else %>
                <%= diapositiva.estilo.nome %>
              <% end %>
            </td>
            <td><%= link_to diapositiva.url,  diapositiva.url, :target => '_blank' %></td>
            <td>
              <%= link_to 'Amosar', diapositiva_path(diapositiva) %>
              <%= image_tag 'amosar3.png', :size => '20x20', :style => 'vertical-align: bottom;' %>
            </td>
            <td>
              <%= link_to 'Editar', edit_diapositiva_path(diapositiva) %>
              <%= image_tag 'editar3.png', :size => '20x20', :style => 'vertical-align: bottom;' %>
            </td>
            <td>
              <%= link_to 'Eliminar', diapositiva, method: :delete, data: { confirm: 'Seguro?' } %>
              <%= image_tag 'eliminar3.png', :size => '20x20', :style => 'vertical-align: bottom;' %>
            </td>
      </tr>
    <% end %>
    </table>
    <%end%>
  </div>
</div>

app/views/diapositivas/new.html.erb
<div id="enlaces">
  <%= link_to 'Volver ó listado de diapositivas', diapositivas_path %>
  <%= link_to 'Xestión de contidos', uploads_path %>
</div>

<div id="paxina">
  <% if !params[:idFormato] %>
    <h2>Formatos dispoñibles</h2>
    <div id="datos">
      
    <% if @formatos.empty?%>
      <p> Non existen formatos!</p>
    <% else %>
    
    <table id=tabla>
      <tr>
        <th> Nome </th>
        <th> Campos </th>
        <th> Subformatos </th>
        <th></th>
      </tr>
    <% @formatos.each do |formato| %>
      <tr>
        <td> <%= formato.nome %> </td>
        
        <!-- Imprimimos os campos que posúe o formato -->
        <td>
          <% formato.campos.each_with_index do |campo,i| %>
              <% if i!=0 %>
              ,
              <% end %>
              <%= campo.tipo %> <%= campo.subtipo %>
          <% end %>
        </td>

        <!-- Formulario para escoller os subformatos desexados -->
        <!-- Imprímense os subformatos de cada campo -->
        <td>
        <%= form_tag new_diapositiva_path, :method => :get do%>
          <% formato.subformatos.each do |subformato| %>
            <%= check_box_tag 'subformato[]', subformato.id %>
            <%= link_to subformato.id, subformato_path(subformato), :target => '_blank'%>
           (<%= subformato.dispositivoloxico.relacionAspectoHorizontal %>:<%= subformato.dispositivoloxico.relacionAspectoVertical %>)
          <br />
          <% end %>
          <%= hidden_field_tag :idFormato, formato.id%>
        </td>
        <td>
          <%= submit_tag "Selecionar", :id => 'selecionFormato'%>
          <% end %>
        </td>
      </tr>
    <% end %>
    </table>
    <% end %>
    </div>

  <% else %>
    <h2>Crear contido </h2>

    <div id="datosConGaleria">
      <h3>Datos</h3>
      <!-- Mensaxe informativa -->
      <p><b>Formato: </b> <%= @formato.nome %> </p>
      <p><b>Subformatos: </b><%= @imprimirSubformatos %></p>
      <p><b>Dispositivos: </b><%= @imprimirDispositivos %></p>

      <!-- Formulario para recoller valores -->
      <%= form_tag diapositivas_path, :id =>'diapositivas', :html => {:multipart => true} do%>
        <%= label_tag 'Nome' %>
        <%= text_field_tag :nome %>

        <h3>Contido</h3>
        <% @formato.campos.zip @rexistros %>
        <% @formato.campos.zip(@rexistros).each_with_index do |(campo,rexistro),i| %>
          <%= label_tag campo.subtipo %>
          <% if campo.subtipo == 'Título' || campo.subtipo == 'Subtítulo' || campo.subtipo == 'Pé' %>
            <%= text_field_tag 'valor[]','', :size => 50 %>
          <% elsif campo.subtipo == 'Resumo' || campo.subtipo == 'Descrición' || campo.subtipo == 'Embebido' %>
            <%= text_area_tag('valor[]', '', :size => "48x5", :resize => "horizontal")%>
          <% else %>
            <div id="selecionContido">
              <p id="cargarGaleria">
                Escoller da galería
                <%= image_tag 'galeria.png', :size => '20x20', :style => 'vertical-align: top;' %>
              </p>
              <div id="galeria">
                <% if campo.tipo == 'Imaxe' %>
                  <%  @imaxes.each do |imaxe| %>
                    <%= image_tag(imaxe.gsub("app/assets/images/", ""), :size => '100x100') %>
                  <% end %>
                <% else %>
                  <%  @videos.each do |video| %>
                    <%= video_tag(video.gsub("public/videos/", ""), :size => "200x200") %></video>
                  <% end %>
                <% end %>
              </div>

              <%= text_field_tag 'valor[]','', :size => 50, :id => 'pathContido' %>
              <p id="explicacion">
                Tam&eacute;n pode facilitar unha ligaz&oacute;n externa.
              </p>
            </div>
          <% end %> <!-- END if tipo campo -->
          <%= hidden_field_tag 'idRexistro[]', rexistro.id %>
        <% end %> <!-- END @formato.campos.each -->

        <!-- Estilo desexado -->
        <%= label_tag 'Estilo' %>
        <% if @estilos.empty? %>
          <p>Non existen estilos!</p>
        <% else %>
          <% @estilos.each do |estilo| %>
            <%= radio_button "estilo", "", estilo.id %> <%= estilo.nome %>
            <%= link_to 'Detalles', estilo_path(estilo), :target => '_blank' %>
            <%= image_tag 'amosar3.png', :size => '20x20', :style => 'vertical-align: top;' %>
          <% end %>
        <% end %>
        <br />
        <!-- Necesítanse os subformatos escollidos -->
        <% @subformatosEscollidos.each do |subformato| %>
          <%= hidden_field_tag 'subformatos[]', subformato %>
        <% end %>
        <%= submit_tag 'Gardar contido' %>
      <% end %> <!-- END form -->
    </div>
  <% end %> <!-- END if-->
</div>

app/views/diapositivas/show.html.erb
<div id="enlaces">
  <%= link_to 'Editar', edit_diapositiva_path(@diapositiva) %>  
  <%= link_to 'Volver ó listado de diapositivas', diapositivas_path %>
</div>

<div id="paxina">
  <h2> Datos </h2>
  <div id="datos">
    <p><b>Nome: </b> <%= @diapositiva.nome %></p>
    <p><b>Url: </b> <%= link_to @diapositiva.url, @diapositiva.url, :target => '_blank' %></p>
    <p><b>Diapositiva con formato: </b><%= @diapositiva_formato.nome %></p>
    <p><b>Diapositiva para dispositivo: </b><%= @diapositiva_dispositivo%></p>
    <p><b>Estilo: </b><%= @diapositiva.estilo.nome %></p>
  </div>

  <h2> Contido </h2>
  <div id="datos">
    <% @diapositiva.campos_formatos_subformatos_diapositivas.zip @diapositiva_campos %>
    <% @diapositiva.campos_formatos_subformatos_diapositivas.zip(@diapositiva_campos).each do |rexistro,campo| %>
      <% @campo = Campo.find(rexistro.campos_formatos_subformatos_campos_formatos_campo_id) %>
      <p><b><%= campo.subtipo %></b></p>
      <% if campo.tipo == 'Imaxe' %>
        <%=  image_tag rexistro.contido, :size => '160x120'%>
      <% elsif campo.tipo == 'Vídeo' %>
        <% if campo.subtipo == 'Local' %>
          <%= video_tag(rexistro.contido, :controls => true)%>
        <% elsif campo.subtipo == 'Embebido' %>
          <%= rexistro.contido.html_safe %>
        <% end %>
      <% else %>
        <p><%= rexistro.contido %></p>
      <% end %>
    <% end %>
  </div>
</div>