config/routes.rb
TFG::Application.routes.draw do

  resources :dispositivofisicos

  resources :parametros

  resources :estilos

  resources :listareproducions

  resources :dispositivoloxicos

  resources :subformatos

  resources :diapositivas

  resources :campos

  resources :formatos

  resources :diapositivas_listareproducions

  resources :uploads
  
  match "/diapositivas_listareproducions/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/listareproducions/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/listareproducions/:id/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/diapositivas/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/diapositivas/:id/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")
  match "/public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")

  match "public/contidos/:diapositiva" => redirect("/contidos/%{diapositiva}")

  match "/listareproducions/public/listas/:lista/:diapositiva" => redirect("/listas/%{lista}/%{diapositiva}")
  match "/listareproducions/:id/public/listas/:lista/:diapositiva" => redirect("/listas/%{lista}/%{diapositiva}")
  match "/public/listas/:lista/:diapositiva" => redirect("/listas/%{lista}/%{diapositiva}")

  match "dispositivofisicos/public/dispositivos/:dispositivo/inicio.html" => redirect("/dispositivos/%{dispositivo}/inicio.html")
  match "/dispositivos/:dispositivo/public/listas/:lista/:diapositiva" => redirect("/listas/%{lista}/%{diapositiva}")
  
  post 'listareproducions/:id/edit', :controller => 'listareproducions', :action => 'edit', :id => '%{id}'
  post 'diapositivas/uploadFile'
  post 'uploads/uploadFile'

  post 'campos/desvincular'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TFG</title>
  <%= javascript_include_tag "previsualizacion" %>
  <%= javascript_include_tag "farbtastic" %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag "farbtastic" %>
  <%= csrf_meta_tags %>
   <link rel="stylesheet" href="farbtastic.css" type="text/css" />
</head>
<body>
  <div id="cabeceira">
    <h1>Display tool</h1>
  </div>

  <div id="menuSuperior">
    <%= link_to 'Dispositivos lóxicos', dispositivoloxicos_path%>
    <%= link_to 'Dispositivos físicos', dispositivofisicos_path%>
    <%= link_to 'Formatos', formatos_path%>
    <%= link_to 'Diapositivas', diapositivas_path%>
    <%= link_to 'Listas de reprodución', listareproducions_path %>
    <%= link_to 'Estilos', estilos_path %>
    <%= link_to 'Arquivos', uploads_path %>
    <%= link_to 'Parámetros de configuración', parametros_path%>
  </div>

  <div id="contido">
    <%= yield %>
  </div>
  
  <%= javascript_include_tag "application" %>
</body>
</html>